# Generated by Django 5.2.3 on 2025-06-11 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='business_unit',
            field=models.ForeignKey(blank=True, help_text='Unidad de negocio a la que pertenece el proveedor', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='tenant.businessunit', verbose_name='Unidad de Negocio'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, help_text='Dirección completa del proveedor', null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='bank_cbu_alias',
            field=models.CharField(blank=True, help_text='CBU o ALIAS bancario para transferencias', max_length=100, null=True, verbose_name='CBU/ALIAS'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Nombre del banco para transferencias', max_length=100, null=True, verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Nombre completo de la persona de contacto principal', max_length=100, null=True, verbose_name='Persona de Contacto'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, help_text='Correo electrónico principal del proveedor', max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='notes',
            field=models.TextField(blank=True, help_text='Notas adicionales sobre el proveedor', null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, help_text='Número de teléfono principal del proveedor', max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['business_unit'], name='suppliers_s_busines_3e42cc_idx'),
        ),
    ]
