# Generated by Django 5.2.3 on 2025-06-15 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_alter_customer_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnitUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text='Indica si esta es la unidad de negocio principal del usuario', verbose_name='Unidad Principal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='tenant.businessunit', verbose_name='Unidad de Negocio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_unit_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Asignación de Usuario a Unidad de Negocio',
                'verbose_name_plural': 'Asignaciones de Usuarios a Unidades de Negocio',
                'ordering': ['user', '-is_primary', 'business_unit__name'],
                'unique_together': {('user', 'business_unit')},
            },
        ),
    ]
