# Generated by Django 5.2.3 on 2025-06-16 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_businessunituser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessunituser',
            options={'ordering': ['user', '-is_primary', 'business_unit__name'], 'verbose_name': 'Usuario y Unidad de Negocio', 'verbose_name_plural': 'Usuarios y Unidades de Negocio'},
        ),
    ]
