# Generated by Django 5.0 on 2025-06-08 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_expenses_is_fixed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='expense_type',
            field=models.ForeignKey(blank=True, help_text='Categoría o tipo de gasto realizado', null=True, on_delete=django.db.models.deletion.PROTECT, to='expenses.expensetype', verbose_name='Tipo de gasto'),
        ),
    ]
