# Generated by Django 5.2.3 on 2025-06-11 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_alter_expenses_expense_type'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='business_unit',
            field=models.ForeignKey(blank=True, help_text='Unidad de negocio a la que pertenece el gasto', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='tenant.businessunit', verbose_name='Unidad de Negocio'),
        ),
    ]
