# Generated by Django 5.2.3 on 2025-06-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_expenses_business_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensetype',
            name='limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Límite máximo permitido para este tipo de gasto', max_digits=10, null=True, verbose_name='Límite'),
        ),
    ]
