# Generated by Django 5.0 on 2025-06-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='currency',
            field=models.CharField(blank=True, default='ARS', max_length=3, null=True, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='income',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='income',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio del producto'),
        ),
        migrations.AlterField(
            model_name='income',
            name='product_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad del producto'),
        ),
        migrations.AlterField(
            model_name='income',
            name='product_subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal de productos'),
        ),
        migrations.AlterField(
            model_name='income',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total'),
        ),
    ]
