# Generated by Django 5.2.3 on 2025-06-11 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0002_alter_income_currency_alter_income_email_and_more'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='business_unit',
            field=models.ForeignKey(blank=True, help_text='Unidad de negocio a la que pertenece la venta', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='tenant.businessunit', verbose_name='Unidad de Negocio'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['business_unit'], name='incomes_inc_busines_9560e0_idx'),
        ),
    ]
