# Generated by Django 5.2.3 on 2025-06-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0003_income_business_unit_and_more'),
        ('tenant', '0002_alter_customer_options'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='income',
            name='incomes_inc_email_e6ccff_idx',
        ),
        migrations.RemoveIndex(
            model_name='income',
            name='incomes_inc_shippin_a195d0_idx',
        ),
        migrations.RemoveField(
            model_name='income',
            name='shipping_date',
        ),
        migrations.AddField(
            model_name='income',
            name='business_type',
            field=models.CharField(choices=[('ecommerce', 'E-commerce'), ('fisico', 'Local físico'), ('mixto', 'Mixto')], default='fisico', max_length=20, verbose_name='Tipo de negocio'),
        ),
        migrations.AlterField(
            model_name='income',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del cliente'),
        ),
        migrations.AlterField(
            model_name='income',
            name='buyer_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas del cliente'),
        ),
        migrations.AlterField(
            model_name='income',
            name='channel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Canal de venta'),
        ),
        migrations.AlterField(
            model_name='income',
            name='currency',
            field=models.CharField(choices=[('ARS', 'Peso Argentino'), ('USD', 'Dólar Estadounidense'), ('EUR', 'Euro'), ('BRL', 'Real Brasileño'), ('CLP', 'Peso Chileno'), ('UYU', 'Peso Uruguayo'), ('PEN', 'Sol Peruano'), ('COP', 'Peso Colombiano'), ('MXN', 'Peso Mexicano')], default='ARS', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='income',
            name='order_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='ID de orden'),
        ),
        migrations.AlterField(
            model_name='income',
            name='order_number',
            field=models.CharField(max_length=30, verbose_name='Número de orden/venta'),
        ),
        migrations.AlterField(
            model_name='income',
            name='order_status',
            field=models.CharField(choices=[('abierta', 'Abierta'), ('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('reembolsada', 'Reembolsada'), ('en_espera', 'En espera'), ('parcialmente_reembolsada', 'Parcialmente reembolsada')], default='abierta', max_length=30, verbose_name='Estado de la orden'),
        ),
        migrations.AlterField(
            model_name='income',
            name='payment_method',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta_credito', 'Tarjeta de crédito'), ('tarjeta_debito', 'Tarjeta de débito'), ('transferencia', 'Transferencia bancaria'), ('mercado_pago', 'Mercado Pago'), ('paypal', 'PayPal'), ('otro', 'Otro')], default='efectivo', max_length=20, verbose_name='Medio de pago'),
        ),
        migrations.AlterField(
            model_name='income',
            name='payment_status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('parcialmente_pagado', 'Parcialmente pagado'), ('reembolsado', 'Reembolsado'), ('fallido', 'Fallido'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado del pago'),
        ),
        migrations.AlterField(
            model_name='income',
            name='payment_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de transacción'),
        ),
        migrations.AlterField(
            model_name='income',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del producto'),
        ),
        migrations.AlterField(
            model_name='income',
            name='registered_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Registrado por'),
        ),
        migrations.AlterField(
            model_name='income',
            name='sales_branch',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sucursal'),
        ),
        migrations.AlterField(
            model_name='income',
            name='shipping_method',
            field=models.CharField(blank=True, choices=[('retiro', 'Retiro en local'), ('envio', 'Envío a domicilio'), ('express', 'Envío express'), ('estandar', 'Envío estándar'), ('no_requiere', 'No requiere envío')], default='no_requiere', max_length=20, null=True, verbose_name='Medio de envío'),
        ),
        migrations.AlterField(
            model_name='income',
            name='shipping_status',
            field=models.CharField(blank=True, choices=[('no_empaquetado', 'No empaquetado'), ('empaquetado', 'Empaquetado'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('devuelto', 'Devuelto'), ('no_requiere', 'No requiere envío')], default='no_requiere', max_length=20, null=True, verbose_name='Estado del envío'),
        ),
        migrations.AlterField(
            model_name='income',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de tracking'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['business_type'], name='incomes_inc_busines_9ff235_idx'),
        ),
    ]
