# Generated by Django 5.2.3 on 2025-06-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0004_remove_income_incomes_inc_email_e6ccff_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='id',
        ),
        migrations.AlterField(
            model_name='income',
            name='order_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='ID de orden'),
        ),
        migrations.AlterField(
            model_name='income',
            name='order_number',
            field=models.CharField(max_length=30, verbose_name='Número de orden/venta/factura'),
        ),
        migrations.AlterField(
            model_name='income',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Total'),
        ),
    ]
