# Generated by Django 5.2.3 on 2025-06-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0005_remove_income_id_alter_income_order_id_and_more'),
        ('tenant', '0002_alter_customer_options'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='income',
            name='incomes_inc_order_i_f75942_idx',
        ),
        migrations.RemoveField(
            model_name='income',
            name='order_id',
        ),
        migrations.AddField(
            model_name='income',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['id'], name='incomes_inc_id_fae2d7_idx'),
        ),
    ]
