# Generated by Django 5.2.3 on 2025-06-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0006_remove_income_incomes_inc_order_i_f75942_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total'),
        ),
    ]
